name: Flutter Windows Build + Setup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.4'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Rename exe
        shell: powershell
        run: |
          Rename-Item `
            "build\windows\x64\runner\Release\c_schollapp.exe" `
            "gestion_de_finance.exe"

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Copy babu.ico for Inno Setup
        shell: powershell
        run: Copy-Item -Path "assets\icons\babu.ico" -Destination "."

      - name: Compile installer
        shell: powershell
        run: |
          $iscc = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          $iss  = "installer.iss"

          if (!(Test-Path $iss)) {
            Write-Error "installer.iss introuvable"
            exit 1
          }

          & "$iscc" "$iss"

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Gestion-de-Finance-Setup
          path: Gestion-de-Finance-Setup.exe

